common/urls.py
from django.urls import path
from . import views
app_name = 'common'

urlpatterns=[
    path('',views.common_index,name = 'index'),
    path('admin',views.common_admin_index,name = 'admin_login'),
    path('seller',views.common_seller_index,name = 'seller_login'),
    path('customer',views.common_customer_index,name = 'customer_login')
]

customer/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('home',views.home),
]

ecom_admin/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('home',views.home)
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

from customer import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('seller/',include('seller.urls')),
    path('ecom_admin/',include('ecom_admin.urls')),
    path('',include('common.urls'))
    
]

seller/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('seller_home',views.home)
]

common/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models

# Create your models here.

ecom_admin/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render

# Create your views here.
def common_index(request):
    return render(request,'common_templates/index.html')

def common_admin_index(request):
    return render(request,'common_templates/admin_index.html')

def common_customer_index(request):
    return render(request,'common_templates/customer_index.html')

def common_seller_index(request):
    return render(request,'common_templates/seller.html')    

customer/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'customer/home.html')

ecom_admin/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'ecom_admin/home.html')

seller/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'seller/home.html')

common/templates/common_templates/admin_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>admin</h1>
    <form action="">
        <table>
            <tr>
                <td>LOGIN</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input type="password"></td>
            </tr>
        </table>
    </form>
</body>
</html>

common/templates/common_templates/customer_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>customer</h1>
    <form action="">
        <table>
            <tr>
                <td>LOGIN</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input type="password"></td>
            </tr>
        </table>
    </form>

</body>
</html>

common/templates/common_templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
  <h1>Common</h1>
  <a href="{% url 'common:admin_login' %}">admin_login</a>
  <a href="{% url 'common:admin_login' %}">seller_login</a>
  <a href="{% url 'common:admin_login' %}">customer_login</a>
</body>
</html>

common/templates/common_templates/seller_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>seller</h1>
    <form action="">
        <table>
            <tr>
                <td>LOGIN</td>
                <td><input type="text"></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input type="password"></td>
            </tr>
        </table>
    </form>
</body>
</html>

customer/templates/customer/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>welcome home</h2>
    
    <img src="{% static 'images/tattoo-design-holding-hands.jpg' %}" >
    <h1>bfkjcshdbkvdfkjhbjgklbhklgj</h1>
</body>
</html>